### ISSUE TITLE
Same result always

### ISSUE THREAD

**Issue by danielmartinezsarta** [penguin-academy/covid-19-py#44]
I've tried the survey many times with answers like a healthy person, an elder with breathing problems, a doctor, a person from risk groups and the result ever is "No es probable que tengas el virus" / "Como usted es parte de un grupo con riesgo de complicaciones".

**Comment by Deeliapatricia** [comment]
The logic is not built yet. We are currently working on that

**Comment by pA1nD** [comment]
@danielmartinezsarta Thanks for reporting! we have deployed the logic now.

Feel free to try again. 👍👀
