### ISSUE TITLE
911 o 154

### ISSUE THREAD

**Issue by mauricioralcala** [penguin-academy/covid-19-py#52]
El gobierno habilito la linea 154 para el COVID-19. 

Puede que sea mejor recomendar el 154 antes que el 911, pero no se como funciona en la práctica esa linea.

https://www.mspbs.gov.py/portal/20589/iquestcomo-se-maneja-el-154-destinado-a-orientaciones-sobre-covid-19.html

The government has implemented a COVID-19 hotline "154". It might be best to recommend that number, rather than "911".

**Comment by mauricioralcala** [comment]
Similarmente, me parece que esta recomendación es incorrecta: 

"Si está en condiciones vaya al hospital para atención médica inmediata."


El gobierno especificamente está pidiendo que la gente no vaya al hospital por riesgo de contagio. Hay que reportar y seguir las instrucciones:

https://www.ultimahora.com/covid-19-sospecha-msp-insta-reportar-y-no-ir-directo-al-hospital-n2873886.html

**Comment by Deeliapatricia** [comment]
Únicamente cuando hay signos de alarma el Ministerio recomienda que busquen ayuda inmediata.

**Comment by pA1nD** [comment]
Currently we show the following:

154 when symptoms
---
<img width="499" alt="Screenshot 2020-03-17 at 23 25 55" src="https://user-images.githubusercontent.com/8961100/76919106-af1d1500-68a6-11ea-8406-1dc11c37c1d4.png">

and 911 when there are alarm signs present
---
<img width="597" alt="Screenshot 2020-03-17 at 23 25 47" src="https://user-images.githubusercontent.com/8961100/76919145-cf4cd400-68a6-11ea-8ead-7b268fb34522.png">

@Deeliapatricia @mauricioralcala 
I think it is ok to show 911 in the case of alarm signs present as it is not a request for advice but an immediate medical urgency is indicated.

Closing this. Feel free to reopen if you don't agree.
