### ISSUE TITLE
Textos para corregir o que están en tercera persona (para cambiarlos a primera)

### ISSUE THREAD

**Issue by diosnelv** [penguin-academy/covid-19-py#69]
- [x] ¿Cuál es ~su~ **tu** sexo?
- [x] Grave dificultad respiratoria, sensación de ahogo, dolor de pecho, fiebre persistente ~mas~ **más** de 72 horas
- [x] ¿Fiebre y Dificultades Respiratorias? ~Usted tiene~ **Tenés** síntomas y puede ser contagioso. 
- [x] Por favor ~llama~ **llamá** al 154 para informar que ~cuentas~ **contás** con estos síntomas.

**Comment by camposcristianeze** [comment]
Todos estos fixes ya se encuentran en la app en `develop` asi que calculo que se puede cerrar este issue
