### ISSUE TITLE
Rango de Edades - Age Range

### ISSUE THREAD

**Issue by Fespinolaprieto** [penguin-academy/covid-19-py#75]
Hello, I think that will be very usefull if the age field will be by Range, because you can find out more quickly the range.

**Comment by ginojunchaya** [comment]
Hello,
Regarding the age ranges, it seems to me an excellent idea.
I propose the following organization:
(0-13) childhood / pre-adolescence,
(13-18) adolescence,
(18-40) young adult,
(40-65) adult older,
(> 65) old age.

**Comment by pA1nD** [comment]
We actually want to have the exact age right now for the analysis and have not found this yet to be a particular problem.
