### ISSUE TITLE
Google+Apple to block Covid Apps. Maybe PWA as the interim?

### ISSUE THREAD

**Issue by camposcristianeze** [penguin-academy/covid-19-py#93]
It seems there will be an established process for covid apps

https://www.google.com/amp/s/www.cnet.com/google-amp/news/apple-google-amazon-block-nonofficial-coronavirus-apps-from-app-stores/

Not sure how long this will take to be approved but in the meantime adding PWA functionality could be an option

**Comment by jmayalag** [comment]
This isn't really an app, so it shouldn't be an issue. It's a web app that is not required to be published through the any store.

**Comment by Deeliapatricia** [comment]
Yes, like Jordan said. It's a web app, no need to push it in any store! 💛 I will close this issue now cause I think its resolved. Please feel free to open in again in case you think it's necessary.
